name: oto_asist
description: Oto Asist Uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Loglardaki hataları çözecek paketler:
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.7
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.5
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/car_data.json
    - .env